[package]
name = "imgui_app"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder-lite = "0.1.0"
image = "0.25.10"
imgui = { version = "0.12.0", features = ["tables-api", "docking", "freetype"] }
imgui-sys = { version = "0.12.0", features = ["docking", "freetype", "use-vcpkg"] }
imgui-sdl2-support = { git = "https://github.com/spindlymist/imgui-sdl2-support" }
imgui-wgpu = "0.28.0"
png = "0.18.1"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
rfd = { version = "0.17.2", default-features = false, features = ["gtk3"] }
sdl2 = { version = "0.38.0", features = ["raw-window-handle", "bundled", "static-link"] }
thiserror = "2.0.18"
wgpu = "29.0.1"
